config/routes.rb
Rails.application.routes.draw do
  get 'coaching/answer'

  get 'coaching/ask'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController
  def ask
  end

  def answer
    @question = params[:query]
    @response = coach_answer(@question)
  end

  private

  def coach_answer(your_question)
    if your_question == "I am going to work!"
      return "Good boy!"
    elsif your_question[your_question.length-1].to_s == "?"
      return "Silly question, get dressed and go to work!"
    else
      return "I don't care, get dressed and go to work!"
    end
  end

  # def coach_answer_enhanced(question)
  #   if question == question.upcase
  #     puts "I can feel you motivation !"
  #     question = question.downcase.capitalize
  #     puts coach_answer(question)
  #   else
  #     puts coach_answer(question)
  #   end
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/views/coaching/answer.html.erb
<h1>Coaching#answer</h1>

<!-- app/views/coaching/home.html.erb -->
</br>
</br>

<h2><%= @question %><span> - you</span></h2>
<h2><%= @response %><span> - The coach</span></h2>
<%= link_to "ask another question", coaching_ask_path %>

app/views/coaching/ask.html.erb
<h1>Coaching#ask</h1>

<form action="/coaching/answer" method="get">
  <input type="text" name="query" placeholder="What do you want to ask to your coach ?">
  <input type="submit">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h2>You are in your virtual stupid coaching application !</h2>
    <%= yield %>
  </body>
</html>